import type { Metadata } from "next";

import Navbar from "@/components/Navbar";
import Footer from "@/components/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
      <>
        <Navbar/>
        {children}
        
        <Footer/>
        
      </>

  );
}
